### ISSUE TITLE
List of regions needs updating for codeengine in text

### ISSUE THREAD

**Issue by LB0106** [ibm-cloud-docs/codeengine#11]
https://cloud.ibm.com/docs/codeengine?topic=codeengine-ha-dr

Text at top of page needs updating as only references 3 of the 6 regions available:
_"IBM Cloud™ Code Engine is a GA service that is offered in Dallas, Frankfurt, and Tokyo. "_

**Comment by foverby** [comment]
Thank you.... will address in our next update.

**Comment by foverby** [comment]
Comment addressed and in latest update here:  https://cloud.ibm.com/docs/codeengine?topic=codeengine-ha-dr
