### ISSUE TITLE
Limits and quotas for Code Engine

### ISSUE THREAD

**Issue by roothema** [ibm-cloud-docs/codeengine#12]
Hi, the documentation says the following: 

> CPU	The total combination for all of the apps and jobs cannot exceed 64 vCPUs.

How does it relate to the maximum number of active instance counts (250)? For instance, if I want to run my application by using 8vCPU for each instance then I can or can't scale it up to 250? 

Would be awesome to have a clearer picture of the limitations in terms of practical examples.

Thanks in advance

**Comment by kersten1** [comment]
You can create 250 active instances of your app as long as the vCPU stays 64 or under. In your example, you cannot scale your app up to 250 as that would require 2000 vCPUs. You can, however, scale up a much smaller app - say one that used only .25vCPU. And these numbers just reflect using an app. If you have jobs, then you must take their vCPU into consideration as well. 

We will look at adding some concrete examples to the doc.
