### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by bbogaert67** [ibm-cloud-docs/codeengine#15]
The link to the "For the most up-to-date prices, see Code Engine pricing." Does not provide any info on pricing and the page has a link returning to this page.
The cost estimator does not include the full list of vCPU/RAM combinations.
No clue where to find actual pricing.

**Comment by kersten1** [comment]
Hello,

You've scrolled the page and found the pricing tier?

<img width="1189" alt="Screen Shot 2022-01-27 at 10 11 44 AM" src="https://user-images.githubusercontent.com/5017946/151404698-174c3676-4b3d-4137-a679-9e2d9d82f94c.png">
 
Or are you looking for specific pricing for the vCPU/RAM combos?

**Comment by bbogaert67** [comment]
Hi Kersten, ok, clear now, it's quite hidden (small) compare to the other offering pricing tables.
The cost estimator is still not aligned with the possible vCPU/Mem combinations.

**Comment by kersten1** [comment]
I will forward that on to our OMs. Thanks!

**Comment by kersten1** [comment]
We have accepted this as a known problem right now and opened an internal issue to track. No date yet on when it will be fixed. Closing this one in favor of the internal issue.
