### ISSUE TITLE
Guide for Custom domain doesn't work in all cases

### ISSUE THREAD

**Issue by LarsIpsen** [ibm-cloud-docs/codeengine#18]
The guide : https://cloud.ibm.com/docs/codeengine?topic=codeengine-deploy-multiple-regions
doesn't works in all use cases. 

In our use case we had domain (example.com) owned by a customer. The Code Engine Apps should be using a subdomain (subdomain.example.com). The customer only want to delegate the subdomain to CIS, the parent domain will still be managed by their own registrar. The CE apps are only deployed in single region, so not the exact same scenario as in the guide.

We tried to follow the guide, but without any success, therefore we are created a ticket: CS2936554.
The solution was quite different from the guide. The main issue was, as long we used the Load Balancer in CIS, then we couldn't establish a TLS connection between CIS and Code Engine.  The solution was to drop the Load balancer and create a CName record, and a page rule in CIS.

I suggest that we investigate what the best practice should be and decide if the current guide shall be updated or if we shall create a new guide for a use case similar ours

**Comment by kersten1** [comment]
thank you for the feedback. We are investigating this issue.

**Comment by kersten1** [comment]
Hello,
We suggest that you take a look at the new custom domain mapping support that was recently release for Code Engine - https://cloud.ibm.com/docs/codeengine?topic=codeengine-domain-mappings. We will be taking another look at the CIS custom domain mapping docs to see what other changes we might make.

Thank you for your input,
Kersten
