### ISSUE TITLE
Explain what the Metrics is used for 

### ISSUE THREAD

**Issue by LarsIpsen** [ibm-cloud-docs/codeengine#19]
On the page: https://cloud.ibm.com/docs/codeengine?topic=codeengine-monitor
There are listed a lot of great metrics, but not all are self explained, and if a CE user doesn't need to be a Kube expert, then it will be useful to give a more comprehensive explanation of what the metrics are used for.

**Comment by foverby** [comment]
Thank you for the feedback. We are investigating this issue.

**Comment by foverby** [comment]
Check out the latest updates - additional information for the metric descriptions.  https://cloud.ibm.com/docs/codeengine?topic=codeengine-monitor
