### ISSUE TITLE
Great Britain is not in the EU.

### ISSUE THREAD

**Issue by jarrodu** [ibm-cloud-docs/codeengine#21]
The docs make is look like Great Britain is in the EU. I understand that the short code `eu-gb` is not going to be changed, but I think it is more respectful to remove EU from any other references to Great Britain.

https://cloud.ibm.com/docs/codeengine?topic=codeengine-regions

-    Asia Pacific Sydney (au-syd) region
-   Asia Pacific Osaka (jp-osa) region
-   Asia Pacific Tokyo (jp-tok) region
-   Brazil Sao Paulo (br-sao) region
-   Canada Toronto (ca-tor) region
-   EU Germany (eu-de) region
-   EU Great Britain (eu-gb) region
-   US East (us-east) region
-   US South (us-south) region

**Comment by foverby** [comment]
Thanks for the info.  Yes.. you are correct. We're making an update for this.

**Comment by foverby** [comment]
Regions topic for Code Engine is updated and live: https://cloud.ibm.com/docs/codeengine?topic=codeengine-regions

**Comment by foverby** [comment]
Closing --  you can reopen if you have questions.  Thanks!
