### ISSUE TITLE
File content with terminal/shell dollar indicator

### ISSUE THREAD

**Issue by HeavyWombat** [ibm-cloud-docs/codeengine#22]
The Python sample content contains a starting dollar sign, which is usually only used to indicate it is a terminal/shell command. It should not be in the file content example for `__main__.py` or `requirements.txt`.

<img width="1023" alt="image" src="https://github.com/ibm-cloud-docs/codeengine/assets/1979133/b470f355-b9b4-4e7e-9402-06e1f590b0fc">

**Comment by data-henrik** [comment]
in at least two docs

**Comment by kersten1** [comment]
yes, I have both of them

**Comment by kersten1** [comment]
These are all fixed now. Let me know if you find any more
