### ISSUE TITLE
CF TO EG

### ISSUE THREAD

**Issue by solorantonio** [ibm-cloud-docs/codeengine#24]
Hello everybody, someone know  what is the process for the migration from Cloud Foundry to Code Engine?

**Comment by kersten1** [comment]
Yup! You can start with these 2 articles - https://www.ibm.com/blog/migrating-cloud-functions-code-to-code-engine/ and https://cloud.ibm.com/docs/codeengine?topic=codeengine-fun-migrate

**Comment by kersten1** [comment]
Closing... Please reopen if you have more questions.
