### ISSUE TITLE
Cannot Set up Code engine

### ISSUE THREAD

**Issue by Zane-dev16** [ibm-cloud-docs/codeengine#26]
During the ibm fullstack course, in the ibm skills network console, on the code engine panel, when I click create project it shows preparing for awhile and then shows error. After several attempts the same occurs. What should I do?

**Comment by foverby** [comment]
Thank you for your inquiry. I hope that your fullstack course was helpful and productive. Regarding your question about creating a Code Engine project, can you provide us a screenshot of the page that is rendered at the time the error occurs? As an alternative, please provide the the exact error message as well as any transaction-id, which is rendered when the error occurs. Perhaps you don’t have the needed permissions to create projects. You can learn more about Code Engine projects here:  https://cloud.ibm.com/docs/codeengine?topic=codeengine-manage-project

**Comment by foverby** [comment]
No response - closing issue
