### ISSUE TITLE
Remove the concept of Kubernetes or "clusters" from the Code Engine intro paragraph

### ISSUE THREAD

**Issue by uwefassnacht** [ibm-cloud-docs/codeengine#3]
https://cloud.ibm.com/docs/codeengine?topic=codeengine-about has this section:

`IBM Cloud Code Engine (or "Code Engine") was developed by IBM with the goal of helping you create modern, source-centric, containerized, and serverless apps and jobs that run on your Kubernetes cluster. The platform is designed to address the needs of developers who just want their code to run. Code Engine abstracts the operational burden of building, deploying, and managing workloads in Kubernetes so that developers can focus on what matters most to them: the source code.`

The wording "your Kubernetes cluster" sounds like "the cluster is owned by you, the customer" or even "you need to bring your Kubernetes cluster, so that we can put Code Engine on it".

I'd like us to remove the word "Kubernetes" or even "cluster" completely from the intro ... and focus on the ease of deploying, running and scaling workloads *without* needing to even understand what a cluster or Kubernetes is.

**Comment by kersten1** [comment]
Moved to internal issue here: https://github.ibm.com/coligo/docs/issues/701

**Comment by kersten1** [comment]
Updated.
